rvm:
  - 1.8.7
  - 2.1.10
  - 2.3.3

gemfile:
  - gemfiles/Gemfile.cucumber-1.3
  - gemfiles/Gemfile.cucumber-2.4
  - gemfiles/Gemfile.cucumber-3.0

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.cucumber-3.0
      rvm: 2.1.10
    - gemfile: gemfiles/Gemfile.cucumber-3.0
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.cucumber-2.4
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.cucumber-1.3
      rvm: 2.3.3 # doesn't work with old RSpec and activesupport
    - gemfile: gemfiles/Gemfile.cucumber-1.3
      rvm: 2.1.10 # doesn't work with old RSpec and activesupport

install:
  # Old Travis CI bundler explodes when lockfile version doesn't match recently bumped version
  - gem uninstall bundler -x -I'
  - gem install bundler --version='=1.12.5'
  # This is the default Travis CI install step
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - mysql -e 'create database IF NOT EXISTS cucumber_factory_test;'

script: bundle exec rake current_rspec

sudo: false

cache: bundler

notifications:
  email:
    - fail@makandra.de
